services:
  db_postgres_github-ci:
    image: postgres
    container_name: db_postgres_github-ci
    restart: always
    ports:
      - "5532:5432"
    volumes:
      - pg_githubb-ci:/var/lib/postgresql/data
    env_file:
      - .env
      
  node_app_github-ci:
    container_name: node_app_github-ci
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db_postgres_github-ci
    env_file:
      - .env